version: '2'
services:
  go.adult-image-detector-dev:
    container_name: adult-image-detector-go-dev
    ports:
     - "9191:9191"
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        tests: "skip_on_build"
    volumes:
    - ../../:/go/src/adult-image-detector
    command: "sh -c 'fresh'"